<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Lab - 2</b></center>    
<pre>


<form>
  <label><b>Name:</b></label>
  <span contenteditable="true" style=" display: inline-block;">Smit Maru</span>
  <br><br>

  <label><b>Enrollment No:</b></label>
  <span contenteditable="true" style="display: inline-block;">23010101161</span>
</form>


#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [1]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [2]:
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)

[1 2 3 4 5]


In [3]:
arr_2 = np.arange(2, 11)
print(arr_2)

[ 2  3  4  5  6  7  8  9 10]


### Step 3. Reshape 1D to 2D Array

In [4]:
arr_2d = np.arange(12).reshape(3, 4)
print(arr_2d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print(arr_2d.size)
print(arr_2d.dtype)
print(arr_2d.ndim) #dimention

12
int32
2


### Step 4. Create a Linspace array

In [6]:
arr_ls = np.linspace(0, 5, 20)
print(arr_ls)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


### Step 5. Create a Random Numbered Array

In [7]:
arr_r = np.random.rand(5)
print(arr_r)

[0.85199473 0.40958552 0.59154038 0.84407658 0.75496985]


In [8]:
arr_2_r = np.random.rand(2, 5)
print(arr_2_r)

[[0.93932318 0.76517792 0.3279605  0.04224219 0.58414288]
 [0.08086957 0.47539208 0.56380551 0.12650827 0.98973303]]


### Step 6. Create a Random Integer Array

In [9]:
arr_r_int = np.random.randint(1, 50, size = 4)
print(arr_r_int)

[16 35 10  6]


### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [10]:
arr_a = np.random.randint(1, 50, size = 15)
print(arr_a)

[25 36 23 26 29 42 26  2 34 31 38 44 46 23 39]


In [11]:
print(arr_a.max())

46


In [12]:
print(arr_a.min())

2


In [13]:
print(arr_a.argmax())

12


In [14]:
print(arr_a.argmin())

7


### Step 8. Indexing in 1D Array

In [15]:
a = np.arange(10)


In [16]:
print(a[0])

0


### Step 9. Indexing in 2D Array

In [17]:
a2d = np.arange(12).reshape(3, 4)

In [18]:
print(a2d[0])

[0 1 2 3]


In [19]:
print(a2d[0, 2])

2


In [20]:
print(a2d[0][2])

2


### Step 10. Conditional Selection

In [21]:
print(a2d[a2d > 4])

[ 5  6  7  8  9 10 11]


In [22]:
print(a2d[a2d % 2 == 0])

[ 0  2  4  6  8 10]


### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [23]:
#pip install pandas-->(already installed, biji vaar karvi nahi, karnaar ne sajaa thase)

In [24]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

In [25]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|')

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [26]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|')

In [27]:
print(users, sep='|')

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]


### Step 4. See the first 25 entries

In [28]:
users.head(25)

user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [29]:
users.tail(10)

user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [30]:
print(users.shape[0])

943


### Step 7. What is the number of columns in the dataset?

In [31]:
print(users.shape[1])

5


### Step 8. Print the name of all the columns.

In [32]:
print(users.columns.tolist())

['user_id', 'age', 'gender', 'occupation', 'zip_code']


### Step 9. How is the dataset indexed?

In [33]:
print(users.index)

RangeIndex(start=0, stop=943, step=1)


### Step 10. What is the data type of each column?

In [34]:
print(users.dtypes)

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object


### Step 11. Print only the occupation column

In [35]:
print(users['occupation'])

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object


### Step 12. How many different occupations are in this dataset?

In [36]:
print(users.columns)


Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')


### Step 13. What is the most frequent occupation?

In [37]:
print(users['occupation'].value_counts().idxmax())

student


### Step 14. Summarize the DataFrame.

In [38]:
print(users.describe())

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000


### Step 15. Summarize all the columns

In [39]:
print(users.describe(include='all'))

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN


### Step 16. Summarize only the occupation column

In [40]:
print(users['occupation'].describe())

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object


### Step 17. What is the mean age of users?

In [41]:
print(users['age'].mean())

34.05196182396607


### Step 18. What is the age with least occurrence?

In [42]:
print(users['age'].value_counts().idxmin())

7


### You're not just learning, you're mastering it. Keep aiming higher! 🚀

In [43]:
print("Yes!....")

Yes!....
