# 🧮 NumPy  — Student Workbook

---

**Duration:** 1.5 Hours  
**Topic:** NumPy — Numerical Computing with Python  
**Level:** Easy → Medium  

---

### 📋 Instructions
- Write your answers in the **blank code cells** below each task.
- Do **not** modify the task description cells.
- Run each cell after writing your answer to verify it works.
- Import NumPy at the start — it is already done for you below.

---

In [1]:
import numpy as np
print('NumPy version:', np.__version__)
print('✅ NumPy imported successfully!')

NumPy version: 1.26.4
✅ NumPy imported successfully!


---
## 🟢 SECTION 1 — Easy (Tasks 1–12)
---

### ✅ Task 1 — Create a 1D Array
Create a NumPy array from the following Python list:  
`[10, 20, 30, 40, 50]`  
Print the array and its **data type**.

In [15]:
# ✏️ Write your answer here
n = int(input("Enter Array Size : "))
list = []
for i in range(n):
    n = int(input("Enter Element : "))
    list.append(n)
print(list)
print(type(list))

Enter Array Size :  2
Enter Element :  5
Enter Element :  4


[5, 4]
<class 'list'>


### ✅ Task 2 — Array of Zeros and Ones
1. Create an array of **5 zeros** (float type).
2. Create an array of **5 ones** (float type).
3. Print both arrays.

In [25]:
# ✏️ Write your answer here
arr1 = np.ones(5)
print(arr1)
arr0 = np.zeros(5)
print(arr0)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


### ✅ Task 3 — Range Array with `arange`
Create an array of all **even numbers from 0 to 20** (inclusive) using `np.arange`.  
Print the result.

In [26]:
# ✏️ Write your answer here
print(np.arange(0,20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### ✅ Task 4 — Linspace
Use `np.linspace` to create an array of **7 evenly spaced values** between `0` and `1`.  
Print the array.

In [28]:
# ✏️ Write your answer here
print(np.linspace(0,1,7))

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


### ✅ Task 5 — Array Shape and Dimensions
Create the following array and print its **shape**, **number of dimensions (ndim)**, and **total number of elements (size)**:
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
```

In [33]:
# ✏️ Write your answer here
arr =  np.arange(1,7)
arr = arr.reshape(2,3)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


### ✅ Task 6 — Array Indexing
Given:
```python
arr = np.array([5, 15, 25, 35, 45, 55])
```
1. Print the **first** element.
2. Print the **last** element.
3. Print the element at index **3**.

In [38]:
# ✏️ Write your answer here
arr = np.array([5, 15, 25, 35, 45, 55])
print(arr[0])
print(arr[-1])
print(arr[3])

5
55
35


### ✅ Task 7 — Array Slicing
Given:
```python
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
```
1. Slice elements from index **2 to 5** (inclusive).
2. Slice the **last 3 elements**.
3. Slice every **other element** (step = 2).

In [46]:
# ✏️ Write your answer here
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[2:6])
print(arr[-1:-4:-1])
print(arr[::2])

[30 40 50 60]
[80 70 60]
[10 30 50 70]


### ✅ Task 8 — Basic Math Operations
Given:
```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
```
Compute and print:
1. `a + b`
2. `b - a`
3. `a * b`
4. `b / a`

In [49]:
# ✏️ Write your answer here
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a+b)
print(a-b)
print(a*b)
print(b/a)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


### ✅ Task 9 — Statistical Functions
Given:
```python
data = np.array([4, 7, 13, 2, 1, 9, 15, 6, 11, 8])
```
Calculate and print:
- **Mean**, **Median**, **Standard Deviation**, **Min**, **Max**

In [54]:
# ✏️ Write your answer here
data = np.array([4, 7, 13, 2, 1, 9, 15, 6, 11, 8])
print(np.min(data))
print(np.max(data))
print(np.std(data))
print(np.mean(data))
print(np.median(data))

1
15
4.340506882842141
7.6
7.5


### ✅ Task 10 — Reshape an Array
Create an array using `np.arange(1, 13)` and reshape it into a **3×4 matrix**.  
Print the reshaped array and its shape.

In [55]:
# ✏️ Write your answer here
arr =  np.arange(1,13)
arr = arr.reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### ✅ Task 11 — Identity and Diagonal Matrix
1. Create a **4×4 identity matrix** using `np.eye`.
2. Extract only the **diagonal elements** from it using `np.diag`.
3. Print both.

In [59]:
# ✏️ Write your answer here
arr = np.eye(4)
print(arr)
print("-----------------------")
print(np.diag(arr))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------------
[1. 1. 1. 1.]


### ✅ Task 12 — Random Array
1. Set random seed to **42** for reproducibility.
2. Generate a **3×3 array** of random integers between **1 and 100** using `np.random.randint`.
3. Print the array.

In [66]:
# ✏️ Write your answer here
np.random.seed(42)
arr = np.random.randint(1,101,(3,3))
print(arr)

[[52 93 15]
 [72 61 21]
 [83 87 75]]


---
## 🟡 SECTION 2 — Medium (Tasks 13–24)
---

### ✅ Task 13 — Boolean Masking
Given:
```python
scores = np.array([45, 78, 90, 32, 55, 88, 67, 23, 95, 40])
```
1. Create a boolean mask for all scores **greater than 60**.
2. Use the mask to extract only those scores.
3. Print the mask and the filtered scores.

In [70]:
# ✏️ Write your answer here
scores = np.array([45, 78, 90, 32, 55, 88, 67, 23, 95, 40])
arr = scores > 60
print(arr)
print(scores[arr])

[False  True  True False False  True  True False  True False]
[78 90 88 67 95]


### ✅ Task 14 — Fancy Indexing
Given:
```python
arr = np.array([100, 200, 300, 400, 500, 600, 700])
```
Use **fancy indexing** to extract elements at indices `[0, 2, 4, 6]`.  
Then replace the element at index `1` with `999`.  
Print both results.

In [72]:
# ✏️ Write your answer here
arr = np.array([100, 200, 300, 400, 500, 600, 700])
print(arr[[0, 2, 4, 6]])
arr[1] = 999
print(arr)

[100 300 500 700]
[100 999 300 400 500 600 700]


### ✅ Task 15 — Stacking Arrays
Given:
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```
1. Stack them **vertically** using `np.vstack`. Print the result.
2. Stack them **horizontally** using `np.hstack`. Print the result.
3. Stack them using `np.column_stack`. Print the result.

In [90]:
# ✏️ Write your answer here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
s = np.vstack(a)
m = np.vstack(b)
print(s,m)

i = np.hstack(a)
t = np.hstack(b)
print(i,t)

m = np.column_stack(a)
a = np.column_stack(b)
print(m,a)

[[1]
 [2]
 [3]] [[4]
 [5]
 [6]]
[1 2 3] [4 5 6]
[[1 2 3]] [[4 5 6]]



### ✅ Task 16 — Splitting Arrays
Create `arr = np.arange(1, 25)` and:
1. Split it into **4 equal parts** using `np.split`. Print each part.
2. Reshape it to `(4, 6)` and split into **2 arrays horizontally** using `np.hsplit`. Print both.

In [94]:
# ✏️ Write your answer here
arr = np.arange(1, 25)
split = np.split(arr,4)
print(split)
print(arr.reshape(4,6))

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24])]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


### ✅ Task 17 — Broadcasting
Given:
```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row    = np.array([10, 20, 30])
```
1. Add `row` to every row of `matrix` using **broadcasting**. Print the result.
2. Multiply the entire `matrix` by scalar `5`. Print the result.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 18 — Sorting
Given:
```python
arr = np.array([3, 1, 9, 5, 2, 8, 4, 7, 6])
```
1. Sort the array in **ascending order**.
2. Sort in **descending order**.
3. Return the **indices that would sort** the array (`np.argsort`).
4. Find the index of the **maximum** and **minimum** values.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 19 — Aggregations Along Axes
Given:
```python
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
```
Calculate:
1. **Sum of each column** (axis=0)
2. **Mean of each row** (axis=1)
3. **Max of the entire matrix**
4. **Cumulative sum** of the flattened matrix

In [ ]:
# ✏️ Write your answer here


### ✅ Task 20 — `where` Condition
Given:
```python
grades = np.array([55, 82, 37, 90, 48, 73, 60, 29, 95, 67])
```
Use `np.where` to create a new array where:
- Grades **>= 60** become the string `'Pass'`
- Grades **< 60** become the string `'Fail'`

Print the result.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 22 — Unique Values and Counting
Given:
```python
data = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 3, 3])
```
1. Find all **unique values**.
2. Find the **count of each unique value**.
3. Find the **index of first occurrence** of each unique value.
*(Use `np.unique` with appropriate parameters)*

In [ ]:
# ✏️ Write your answer here


### ✅ Task 23 — Flatten and Ravel
Given:
```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
```
1. Flatten using `.flatten()` — modify the returned array and check if original changes.
2. Flatten using `.ravel()` — modify the returned array and check if original changes.
3. Explain the difference (as a comment in your code).

In [ ]:
# ✏️ Write your answer here
